- name: Add homebrew taps
  homebrew_tap:
    name: caskroom/cask
- name: Installing homebrew packages
  homebrew:
    name: "{{ brew_packages }}"
    state: "present"
    update_homebrew: yes
- name: Installing Homebrew Cask Packages]
  homebrew_cask:
    name: "{{ brew_cask_packages }}"
    state: "present"
    update_homebrew: yes
- name: Installing pip packages
  pip:
    name: "{{ pip_packages }}"
    state: "present"
    executable: pip2
