- name: Add homebrew taps
  homebrew_tap:
    name: caskroom/cask
- name: Add my homebrew taps
  homebrew_tap:
    name: luizm/homebrew-tap
    url: "https://github.com/luizm/homebrew-tap"
- name: Installing homebrew packages
  homebrew:
    name: "{{ brew_packages }}"
    state: "present"
    update_homebrew: yes
- name: Installing Homebrew Cask Packages]
  homebrew_cask:
    name: "{{ brew_cask_packages }}"
    state: "present"
    update_homebrew: yes
- name: Installing pip packages
  pip:
    name: "{{ pip_packages }}"
    state: "present"
    executable: pip2
